class RunPassportsController < ApplicationController
  before_action :set_passport, only: [:show, :run_council, :generate_document, :export, :set_review_mode]
  before_action :require_current_project, only: :index

  def index
    @passports = current_project.run_passports.includes(:workstream).order(created_at: :desc)
  end

  def show
    @versions = @passport.passport_versions.includes(:agent_session).latest_first
    @council_reviews = @passport.council_reviews.ordered
  end

  def run_council
    CouncilRunner.new(@passport).run!
    @passport.create_version!(trigger: "council_completed")
    redirect_to run_passport_path(@passport, anchor: "council"), notice: council_notice
  end

  def set_review_mode
    @passport.update!(review_mode: params[:mode])

    case params[:mode]
    when "full_council"
      CouncilRunner.new(@passport).run!
      @passport.create_version!(trigger: "council_completed")
      redirect_to run_passport_path(@passport, anchor: "council"), notice: council_notice
    when "smart_summary"
      used_llm = PassportGenerator.new(@passport.workstream).apply_smart_summary!(@passport)
      @passport.create_version!(trigger: "manual_assessment")
      notice = if used_llm
        "Smart summary generated by AI (#{LlmClient::SUMMARY_MODEL})."
      else
        "Smart Summary mode set. Add an ANTHROPIC_API_KEY to enable AI summaries."
      end
      redirect_to run_passport_path(@passport), notice: notice
    else
      redirect_to run_passport_path(@passport), notice: "Review mode set to #{@passport.review_mode_label}."
    end
  end

  def generate_document
    generator = DocumentGenerator.new(@passport)
    case params[:doc_type]
    when "adr"
      doc = generator.generate_adr!
      redirect_to document_path(doc), notice: "ADR draft generated."
    when "decision_log"
      log = generator.generate_decision_log!
      redirect_to decision_log_path(log), notice: "Decision log generated."
    when "pr_summary"
      doc = generator.generate_pr_summary!
      redirect_to document_path(doc), notice: "PR summary generated."
    when "memory"
      generator.generate_memory_item!
      redirect_to memory_items_path, notice: "Memory item saved."
    else
      redirect_to run_passport_path(@passport), alert: "Unknown document type."
    end
  end

  def export
    respond_to do |format|
      format.json { render json: passport_json }
      format.any do
        send_data passport_markdown, filename: "passport-#{@passport.id}.md", type: "text/markdown"
      end
    end
  end

  private

  def council_notice
    if LlmClient.enabled?
      "AI Council review completed (#{LlmClient::COUNCIL_MODEL})."
    else
      "Council review completed using StaffOS heuristics. Add an ANTHROPIC_API_KEY to enable AI reviewers."
    end
  end

  def set_passport
    # RunPassport has no project_id; reach it through its workstream.
    @passport = RunPassport.joins(:workstream)
      .where(workstreams: { project: accessible_projects }).find(params[:id])
  end

  def passport_json
    {
      id: @passport.id,
      intent: @passport.intent,
      summary: @passport.summary,
      risk_level: @passport.risk_level,
      readiness_score: @passport.readiness_score,
      human_review_required: @passport.human_review_required,
      test_summary: @passport.test_summary,
      files_touched: @passport.files_touched,
      missing_checks: @passport.missing_checks,
      recommended_actions: @passport.recommended_actions,
      agent: @passport.agent_sessions.order(:started_at).last&.agent_name,
      branch: @passport.workstream.branch_name,
      sessions: @passport.sessions_count,
      created_at: @passport.created_at
    }
  end

  def passport_markdown
    <<~MD
      # Run Passport ##{@passport.id}

      **Intent:** #{@passport.intent}
      **Agent:** #{@passport.agent_sessions.order(:started_at).last&.agent_name}
      **Branch:** #{@passport.workstream.branch_name}
      **Captured sessions:** #{@passport.sessions_count}
      **Risk Level:** #{@passport.risk_level}
      **Readiness:** #{@passport.readiness_score}%
      **Human Review:** #{@passport.human_review_required? ? 'Required' : 'Not required'}

      ## Summary

      #{@passport.summary}

      ## Files Touched

      #{(@passport.files_touched || []).map { |f| "- `#{f['path']}` (+#{f['additions']}, -#{f['deletions']})" }.join("\n")}

      ## Test Evidence

      #{@passport.test_summary.present? ? "Status: #{@passport.test_summary['status']}, Total: #{@passport.test_summary['total']}, Failed: #{@passport.test_summary['failed']}" : "No test evidence captured."}

      ## Missing Checks

      #{(@passport.missing_checks || []).map { |c| "- [#{c['severity'].upcase}] #{c['check']}" }.join("\n").presence || "None"}

      ## Recommended Actions

      #{(@passport.recommended_actions || []).map { |a| "- [ ] #{a['action']} (#{a['priority']})" }.join("\n").presence || "None"}
    MD
  end
end
